apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "authgear.nameBackground" . | quote }}
  labels:
    {{- include "authgear.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.authgear.background.replicas }}
  selector:
    matchLabels:
      {{- include "authgear.backgroundSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "authgear.backgroundSelectorLabels" . | nindent 8 }}
    spec:
      volumes:
      {{- if .Values.authgear.appCustomResources.path }}
      - name: custom-resources
        {{- toYaml .Values.authgear.appCustomResources.volume | nindent 8 }}
      {{- end }}
      {{- if .Values.authgear.extraVolumes }}
      {{- toYaml .Values.authgear.extraVolumes | nindent 6 }}
      {{- end }}
      {{- if .Values.authgear.background.nodeSelector }}
      nodeSelector:
        {{- .Values.authgear.background.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.authgear.background.nodeName }}
      nodeName: {{ .Values.authgear.background.nodeName | quote }}
      {{- end }}
      {{- if .Values.authgear.background.affinity }}
      affinity:
        {{- .Values.authgear.background.affinity | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.authgear.background.tolerations }}
      tolerations:
      {{- .Values.authgear.background.tolerations | toYaml | nindent 6 }}
      {{- end }}
      {{- if .Values.authgear.background.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- .Values.authgear.background.topologySpreadConstraints | toYaml | nindent 6 }}
      {{- end }}
      containers:
      - name: authgear-background
        image: {{ .Values.authgear.mainServer.image | quote }}
        imagePullPolicy: Always
        args: ["authgear", "background"]
        volumeMounts:
        {{- if .Values.authgear.appCustomResources.path }}
        - name: custom-resources
          mountPath: {{ .Values.authgear.appCustomResources.path | quote }}
        {{- end }}
        {{- if .Values.authgear.extraVolumeMounts }}
        {{- toYaml .Values.authgear.extraVolumeMounts | nindent 8 }}
        {{- end }}
        env:
        - name: DATABASE_URL
          value: {{ .Values.authgear.databaseURL | quote }}
        - name: DATABASE_SCHEMA
          value: {{ .Values.authgear.databaseSchema | quote }}
        - name: REDIS_URL
          value: {{ .Values.authgear.redisURL | quote }}
        - name: DENO_ENDPOINT
          value: {{ printf "http://%s" (include "authgear.nameDeno" .) | quote }}
        - name: TRUST_PROXY
          value: {{ .Values.authgear.trustProxy | quote }}
        - name: LOG_LEVEL
          value: {{ .Values.authgear.logLevel | quote }}
        - name: SENTRY_DSN
          value: {{ .Values.authgear.sentryDSN | quote }}
        - name: CONFIG_SOURCE_TYPE
          value: {{ .Values.authgear.configSourceType | quote }}
        - name: CONFIG_SOURCE_KUBE_NAMESPACE
          value: {{ .Values.authgear.appNamespace | quote }}
        - name: CUSTOM_RESOURCE_DIRECTORY
          value: {{ .Values.authgear.appCustomResources.path | quote }}
        {{- range $key, $val := .Values.authgear.mainServer.env }}
        - name: {{ $key | quote }}
          value: {{ $val | quote }}
        {{- end }}
        resources:
          {{- toYaml .Values.authgear.background.resources | nindent 10 }}
