{{- $secretName := include "authgear.nameWildcard" . }}
{{- if .Values.authgear.tls.wildcard.secretName }}
{{- $secretName = .Values.authgear.tls.wildcard.secretName }}
{{- end }}

{{- if .Values.authgear.ingress.enabled }}

{{- if .Values.authgear.tls.wildcard.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "authgear.nameWildcard" . }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.authgear.ingress.class | quote }}
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
  labels:
    {{- include "authgear.labels" . | nindent 4 }}
spec:
  {{- if .Values.authgear.tls.wildcard.ingress.tls.enabled }}
  tls:
  - secretName: {{ $secretName | quote }}
    hosts:
    - {{ printf "*.%s" .Values.authgear.baseHost | quote }}
  {{- end }}
  rules:
  - host: {{ printf "*.%s" .Values.authgear.baseHost | quote }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "authgear.nameMain" . | quote }}
            port:
              name: http
      - path: /_api/admin
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "authgear.nameAdmin" . | quote }}
            port:
              name: http
      - path: /_resolver
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "authgear.nameResolver" . | quote }}
            port:
              name: http
      - path: /_images
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "authgear.nameImages" . | quote }}
            port:
              name: http
{{- end }}

{{- if .Values.authgear.certManager.enabled }}
{{- if .Values.authgear.tls.wildcard.certManager.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "authgear.nameWildcard" . }}
  labels:
    {{- include "authgear.labels" . | nindent 4 }}
spec:
  secretName: {{ $secretName | quote }}
  dnsNames:
  - {{ printf "*.%s" .Values.authgear.baseHost | quote }}
  - {{ .Values.authgear.baseHost | quote }}
  issuerRef:
    name: {{ .Values.authgear.certManager.issuer.dns01.name | quote }}
    kind: {{ .Values.authgear.certManager.issuer.dns01.kind | quote }}
    group: {{ .Values.authgear.certManager.issuer.dns01.group | quote }}
{{- end }}
{{- end }}

{{- end }}
